GetLabel controller
boostcamp-2020/IssueTracker-34 pull request #122
Opened 2020-11-04 12:01 UTC by gyim1345

Add controller for GET /label

2020-11-04 12:33 UTC, pieisland approved these changes

2020-11-04 14:11 UTC, rockpell requested changes
label.service require한 변수의 이름이

2020-11-04 14:11 UTC, rockpell commented on back/src/controllers/label.controller.js
> +const transactionService = require('../services/label.service');
transactionService로 하신 변수 이름 변경이 필요하지 않을까 싶습니다!

2020-11-04 14:57 UTC, gyim1345 commented on back/src/controllers/label.controller.js
> +const transactionService = require('../services/label.service');
수정했습니다! 복붙하다 걸렸네요 ㅋㅋ

2020-11-04 15:03 UTC, profornnan approved these changes

2020-11-05 03:27 UTC, rockpell approved these changes

2020-11-05 04:03 UTC, merged