Github Oauth
boostcamp-2020/IssueTracker-34 pull request #124
Opened 2020-11-04 12:03 UTC by gyim1345

install passport and github strategy

setup passport configuration for github OAuth authorization

2020-11-04 15:13 UTC, profornnan requested changes

2020-11-04 15:13 UTC, profornnan commented on back/src/middleware/passport.js
> +},
혹시 callbackURL 부분도 `.env` 파일로 관리해보면 어떨까요? 저번 프로젝트에서 테스트할 때와 배포할 때 해당 URL이 달라져서 저도 `.env` 파일로 따로 분리했던 기억이 있네요

2020-11-04 15:26 UTC, profornnan approved these changes

2020-11-05 03:29 UTC, rockpell approved these changes

2020-11-05 06:39 UTC, pieisland approved these changes

2020-11-05 06:39 UTC, gyim1345 commented on back/src/middleware/passport.js
> +},
수정했습니다!

2020-11-05 06:40 UTC, merged