Axios로 label api 호출해 label list 받아오기
boostcamp-2020/IssueTracker-34 pull request #164
Opened 2020-11-09 08:55 UTC by pieisland

- axios와 useEffect를 사용해 데이터베이스에 들어있는 label 값들을 받아왔습니다.
- 이슈 리스트 페이지의 LabelFilterButton과 이슈 상세 페이지의 LabelSelector에 적용했습니다.
- 지금은 useState로 label 상태를 관리하기 때문에 후에 useContext를 사용할 때 수정이 필요해 보입니다.

2020-11-09 09:44 UTC, gyim1345 requested changes
api 요청 async await으로 수정 부탁드립니다!

2020-11-09 09:44 UTC, gyim1345 commented on front/src/components/LabelsSelector.js
> +
서버와 비슷하게 async/await으로 통일하면 좋을것 같습니다!

2020-11-09 10:24 UTC, profornnan requested changes

2020-11-09 10:24 UTC, profornnan commented on front/src/components/LabelFilterButton.js
> +};
저도 이슈 목록 페이지에서 API 요청하는 부분을 구현하다가 든 생각인데 API 요청 함수를 따로 디렉터리를 만들어서 관리해도 좋을 것 같아요!!

2020-11-10 06:09 UTC, gyim1345 approved these changes
수고하셨습니다!

2020-11-10 06:29 UTC, rockpell approved these changes
수고하셨습니다!

2020-11-10 06:29 UTC, profornnan approved these changes
고생하셨습니다!!

2020-11-10 06:34 UTC, merged